### PR TITLE
cleanup tickers

### PR DESCRIPTION
**Pull request by maxtaco**

### CODE REVIEW

**Comment by maxtaco** [comment]
@zapu can you take a look at this?

**Comment by zapu** [comment]
that looks good, and was totally hidden because of use of `rv`. good find

**Comment by zapu** [comment]
these timeouts would eventually fire though, so they wouldn't be holding resources forever.

or is there another side effect of not doing `clearTimeout`?

**Comment by maxtaco** [comment]
No, it's just to clean up the resources, nothing wrong with it as is, just might be wasteful.

**Pull request merged**
